name: GL-Illumina-metagenomics
channels:
    - conda-forge
    - bioconda
    - defaults
    - biobakery
    - astrobiomike
dependencies:
    - fastqc=0.11.9
    - multiqc=1.8
    - bbmap=38.86
    - megahit=1.2.9
    - bit=1.8.11
    - bowtie2=2.3.5.1
    - samtools=1.9
    - prodigal=2.6.3
    - kofamscan=1.3.0
    - blast=2.9.0
    - cat=5.1.2
    - humann=3.0.0.alpha.3
    - diamond=0.9
    - metaphlan=3.0.4
    - snakemake=5.5.4
